name: NotchCraft
author: buildcarter8
version: 1.5-PR1
main: me.buildcarter8.NotchCraft.Notchcraft
commands:
  notchcraft:
         description: Main Command.
         usage: /<command>
  staff:
     description: Staff management
     usage: /<command>
